<a href="https://colab.research.google.com/github/kahinasassi/initial-text-preprocessing--arabic-dialect-/blob/master/traitement_de_la_langue_arabe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import nltk
from nltk import re
from nltk import defaultdict
import io
from nltk import  word_tokenize
from nltk import  sent_tokenize
from nltk.corpus import stopwords
import codecs
import csv
import pickle
from gensim.parsing.preprocessing import strip_short

nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
#vérifie si l'encodage est utf_8
def check_utf8(filename): 
        try:
            f = codecs.open(filename, encoding='utf-8', errors='strict')
            for line in f:
                pass
            return 1 #valid utf_8
        except UnicodeDecodeError:
            return 0 #invalid utf_8

# ouvrir un fichier text
def open_txt_file(chemin):
    #open text file atfter checking if its utf_8  encoding    
    check=check_utf8(chemin)
    if(check == 1):
        f = io.open(chemin,'r',encoding='utf8')
    elif(check == 0):
        f = io.open(chemin,'r')
    return f.read()

# convertir un text vers une liste
def text_to_list(chemin):
    text=open_txt_file(chemin)
    liste=[]
    liste=text.split("\n")
    return liste

# ouvrir un fichier pickle
def open_pickle(path):
  with open(path, 'rb') as handle: 
    doc= pickle.load(handle)
    return doc

def save_pickle(variable,filename):
    with open(filename, 'wb') as handle:
         pickle.dump(variable, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
pip install unidecode

     |████████████████████████████████| 245kB 2.7MB/s 


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
def naive_bayes(data):
  # Set up training and test sets by choosing random samples from classes
  X_train, X_test, y_train, y_test = train_test_split(data['text'].values, data['label'].values, test_size=0.20, random_state=0)
  model = MultinomialNB()
  vect = CountVectorizer()
  vect.fit_transform(data['text'].values)  #train the vectorizer, build the vocablury
  tfidf_transformer=TfidfTransformer()
  X_train_tfidf=vect.transform(X_train)
  X_test_vect=vect.transform(X_test)
  model.fit(X_train_tfidf,y_train)
  model.score(X_train_tfidf,y_train)
  y_pred = model.predict(X_test_vect)
  y_pred
  from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
  print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
  print("\nCOnfusion Matrix:\n", confusion_matrix(y_test, y_pred))

#Evaluation de la traduction

In [ ]:
data=open_pickle("/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/data_traduit.pickle")
for indice  in list(data.index.values): 
    text=str(data['text'][indice])
    data['text'][indice]=text
naive_bayes(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


Accuracy: 68.61%

COnfusion Matrix:
 [[ 817  140  283]
 [ 240  744  271]
 [ 181  123 1145]]


#Evaluation du groupement phonitique

In [ ]:
data=open_pickle("/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/donnee_phonetics.pickle")
for indice  in list(data.index.values): 
    text=str(data['text'][indice])
    data['text'][indice]=text
naive_bayes(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


Accuracy: 70.51%

COnfusion Matrix:
 [[ 838  119  305]
 [ 199  739  328]
 [ 171  112 1373]]


#Evaluation de la translatération

In [ ]:
data=open_pickle("/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/donne_yamli.pickle")
for indice  in list(data.index.values): 
    text=str(data['text'][indice])
    data['text'][indice]=text
naive_bayes(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


Accuracy: 69.77%

COnfusion Matrix:
 [[ 831  151  256]
 [ 229  777  303]
 [ 188  138 1311]]


#Traitement de la langue arabe

In [ ]:
url="/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/stopwrd.txt"
stopwords= text_to_list(url)

# traitement de la langue arabe



In [ ]:
import re
from unidecode import unidecode

def tokenization(text):
    return set(word_tokenize(text)) 

def is_arabizi(text):
    html = len(re.findall(r'[A-Za-z0-9]+',text))
    if(html>0):
      text = unidecode(text)
      return text.replace(text, f' ')
    else:
      return text

def remove_fr(texte):
   word= tokenization(texte) 
   x=str(texte)
   for val in word:
     tt=is_arabizi(val)
     x = x.replace(val, tt)
   return x 
def remove_ponctuation(text):
   puncts = [',', '.', '"', ':', ')', '(', '-', '|', ';', "'", '$', '&', '/', '[', ']', '>', '%', '=', '#', '*', '+', '\\', '•',  '~', '£', 
 '·', '_', '{', '}', '©', '^', '®', '`',  '<', '→', '°', '€', '™', '›',  '♥', '←', '×', '§', '″', '′', 'Â', '█', '½', 'à', '…', 
 '“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║', '―', '¥', '▓', '—', '‹', '─', '،','؟','/',
 '▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è', '¸', '¾', 'Ã', '⋅', '‘', '∞', 
 '∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗',' ️�','▬', '❤', 'ï', 'Ø', '¹', '≤', '‡', '√', ]
   
   x = str(text)
   for punct in puncts:
      if punct in x:
          x = x.replace(punct, f' ')
   return x
arabic_diacritics = re.compile("""
                             ّ    | # Tashdid
                             َ    | # Fatha
                             ً    | # Tanwin Fath
                             ُ    | # Damma
                             ٌ    | # Tanwin Damm
                             ِ    | # Kasra
                             ٍ    | # Tanwin Kasr
                             ْ    | # Sukun
                             ـ     # Tatwil/Kashida
                         """, re.VERBOSE)

def remove_diacritics(text):
    text = re.sub(arabic_diacritics, '', text)
    return text

def remove_arabic_ponctuation(text):
   puncts = ['﴿', '﴾', '۩‎', '۞', '۝', '(', '-', '۔‎', '٭', "؟‎", '؞', '؛‎', '؏', '؎', '؍', '،', '؆', '؇', '؈', '؄', '؁', '؀']
   x = str(text)
   for punct in puncts:
      if punct in x:
          x = x.replace(punct, f' ')
   return x

def normalize_arabic(text):
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ي", "ى", text)
    text = re.sub("ؤ", "ء", text)
    text = re.sub("ئ", "ء", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("گ", "ك", text)
    return text  

def remove_stop_wrd(texte):
  word= tokenization(texte) 
  x=str(texte)
  ma_lis=[]
  for val in word:
    for text  in  stopwords: 
      if(val == text):
        x = x.replace(val,'')  
  return x  
all_dz_msa_stopwords=open_pickle("/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/all_dz_msa_stopwords.pickle")
def remove_stop_words(texte):

  word= tokenization(texte) 
  x=str(texte)
  ma_lis=[]
  for val in word:
    for text  in  all_dz_msa_stopwords: 
      if(val == text):
        x = x.replace(val,'')  
  return x  
def remove_short(text):
  lower_word=text.lower()
  liste=tokenization(lower_word)
  sentence=''
  for word in liste:
    if(len(word) == 1):
        new=''
        sentence=sentence+''+new
    else:
      if(sentence == ''):
        new=word
        sentence=sentence+''+new
      else:
        new=word
        sentence=sentence+' '+new
      
  return sentence
  


In [ ]:
data["text"] = data.text.map(lambda x: remove_short(x)) # suppression des mots court --------------------- Accuracy: 67.97%
naive_bayes(data)

Accuracy: 70.22%

COnfusion Matrix:
 [[ 831  141  266]
 [ 222  782  305]
 [ 184  128 1325]]


In [ ]:
'''data["text"] = data.text.map(lambda x: remove_fr(x)) # suppression des mots fr_arabe -----------------------Accuracy: 68.35%
data["text"] = data.text.map(lambda x: remove_fr(x))# on laisse tous Accuracy: 68.11%
naive_bayes(data)'''

'data["text"] = data.text.map(lambda x: remove_fr(x)) # suppression des mots fr_arabe -----------------------Accuracy: 68.35%\ndata["text"] = data.text.map(lambda x: remove_fr(x))# on laisse tous Accuracy: 68.11%\nnaive_bayes(data)'

# remove_diacritics

In [ ]:
data["text"] = data.text.map(lambda x: remove_diacritics(x))
naive_bayes(data)

Accuracy: 70.29%

COnfusion Matrix:
 [[ 831  140  267]
 [ 220  785  304]
 [ 182  130 1325]]


# remove_arabic_ponctuation

In [ ]:
data["text"] = data.text.map(lambda x: remove_arabic_ponctuation(x))
naive_bayes(data)

Accuracy: 70.29%

COnfusion Matrix:
 [[ 831  140  267]
 [ 220  785  304]
 [ 182  130 1325]]


# normalize_arabic

In [ ]:
data["text"] = data.text.map(lambda x: normalize_arabic(x))
naive_bayes(data)

Accuracy: 70.34%

COnfusion Matrix:
 [[ 828  142  268]
 [ 221  785  303]
 [ 175  132 1330]]


# remove_stop_words

In [ ]:
data["text"] = data.text.map(lambda x: remove_stop_words(x))
naive_bayes(data)

Accuracy: 69.72%

COnfusion Matrix:
 [[ 813  152  273]
 [ 214  766  329]
 [ 162  137 1338]]


In [ ]:
data=open_pickle("/content/drive/My Drive/PROJET FIN ETUDE 2019 2020/ressources/finale_data.pickle")
